# Generated by Django 5.1.7 on 2025-03-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateTimeField()),
                ('marcador', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deportes.campeonato')),
            ],
        ),
    ]
